"""
Compliance models for AML/ID verification and Source of Funds processing.

CRITICAL DESIGN PRINCIPLE:
- All statuses are DETERMINISTIC (from provider or defaulted to REVIEW_REQUIRED)
- LLM is used ONLY for generating human-readable draft summaries
- LLM NEVER decides statuses or gate eligibility
"""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field
from datetime import datetime


class Provider(str, Enum):
    """Supported compliance check providers."""
    THIRDFORT = "thirdfort"
    CREDAS = "credas"
    OTHER = "other"


class CheckType(str, Enum):
    """Type of compliance check being performed."""
    ID_AML = "ID_AML"
    SOF = "SOF"
    BOTH = "BOTH"


class DeterministicStatus(str, Enum):
    """
    Status values for compliance checks.
    These are ALWAYS set deterministically from provider data or defaulted.
    The LLM NEVER sets these values.
    """
    NOT_STARTED = "NOT_STARTED"
    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ProviderStatusPayload(BaseModel):
    """
    Optional structured status from the compliance provider.
    If provided, these values are the source of truth for statuses.
    """
    provider_reference_id: Optional[str] = None
    id_aml_status: Optional[DeterministicStatus] = None
    sof_status: Optional[DeterministicStatus] = None
    flags: list[str] = Field(default_factory=list)
    red_flags_found: Optional[bool] = None
    last_updated_at: Optional[str] = None


class DeterministicComplianceState(BaseModel):
    """
    The deterministic compliance state computed from provider data.
    This is the source of truth for all compliance decisions.
    """
    matter_id: str
    provider: Provider
    provider_reference_id: Optional[str] = None
    id_aml_status: DeterministicStatus
    sof_status: DeterministicStatus
    red_flags_found: bool
    provider_flags: list[str] = Field(default_factory=list)
    missing_items: list[str] = Field(default_factory=list)
    computed_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")


class GateEligibility(BaseModel):
    """
    Deterministic gate eligibility computed from compliance state.
    Both conditions must be met: status PASSED AND no red flags.
    """
    aml_eligible: bool
    sof_eligible: bool
    fully_eligible: bool


class ArtifactMetadata(BaseModel):
    """Metadata about an uploaded document."""
    filename: str
    content_type: str
    size_bytes: int
    page_count: Optional[int] = None
    extracted_chars: int = 0


class LLMDraftSummary(BaseModel):
    """
    Draft compliance summary generated by LLM.
    This is for HUMAN REVIEW ONLY - it does not set any statuses.
    """
    draft_label: str = "Draft — requires solicitor review"
    compliance_summary_short: str
    key_flags: list[str] = Field(default_factory=list)
    missing_evidence: list[str] = Field(default_factory=list)
    confidence_note: str
    generated_at: str
    model_info: Optional[str] = None
    fallback_used: bool = False


class ComplianceIngestResponse(BaseModel):
    """Full response from the compliance ingest endpoint."""
    success: bool
    matter_id: str
    deterministic_state: DeterministicComplianceState
    gate_eligibility: GateEligibility
    llm_draft: Optional[LLMDraftSummary] = None
    fallback_summary_used: bool = False
    artifacts: list[ArtifactMetadata] = Field(default_factory=list)
    message: str


class StoredComplianceRecord(BaseModel):
    """Record stored in the compliance store for later retrieval."""
    matter_id: str
    deterministic_state: DeterministicComplianceState
    gate_eligibility: GateEligibility
    llm_draft: Optional[LLMDraftSummary] = None
    artifacts: list[ArtifactMetadata] = Field(default_factory=list)
    stored_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
